controller:
  serviceAccount:
    create: false
    name: ${service_account_name}

  replicaCount: 2

  region: ${region}

storageClasses:
  - name: gp3
    annotations:
      storageclass.kubernetes.io/is-default-class: "true"
    volumeBindingMode: WaitForFirstConsumer
    reclaimPolicy: Delete
    parameters:
      type: gp3
      encrypted: "true"
