serviceAccount:
  create: false
  name: external-secrets-sa

controller:
  logLevel: info
  metrics:
    enabled: true
  health:
    enabled: true
  securityContext:
    fsGroup: 65534
    runAsUser: 65534

webhook:
  enabled: true
  port: 9443
  service:
    type: ClusterIP
  securityContext:
    fsGroup: 65534
    runAsUser: 65534

aws:
  region: ${region}
  auth:
    type: "jwt"
    jwt:
      serviceAccountRef:
        name: ${service_account_name}
        namespace: ${namespace}

env:
  LOG_LEVEL: info
  METRICS_PORT: 8080

rbac:
  create: true